### ISSUE TITLE
初期コードの整備 - single.php

### ISSUE THREAD

**Issue by kobayash** [liginc/wordpress-frontplate#12]
single.phpに必要な基本的な記述を挙げて行きましょう。

[よく使う]

- タイトル
- 日付
- 本文
- アイキャッチ
- shareまわり?
- メインカテゴリー ?
- タグのリスト?
- この記事書いた人
- 前後の記事
- 関連記事
- 記事詳細のページネーション（プラグインかな）
- 記事詳細の時のパンくずリスト（プラグインかな）

[あまり使わない]

**Comment by zuyadoc** [comment]
- ユーザ情報の取得が新旧の情報が複雑でいつも忘れるからあると嬉しいかも
- アイキャッチだけどsrcだけ使うパターン

**Comment by 82mou** [comment]
関係ないかもしれないのですが、前後の記事は「次の記事」と表記する時と「タイトル」で表記する時がありますね！

**Comment by kobayash** [comment]
@zuyadoc @82mou 
貴重なご意見ありがとうございます…！些細なことでもどんどんお願いします！

**Comment by kobayash** [comment]
> WP_Userへのアクセスは基本的にpropertyへのアクセスのみで事足りる。propertyがなければマジックメソッドによって、ユーザーテーブル及びユーザーメタを探してくれる。
> つまり、
> // $user_info is WP_User object
> $user_info->user_login は $user_info->data->user_login の短縮形で、
> $user_info->rich_editing は get_user_meta( $user_info->ID, 'rich_editing', true ) の短縮形です。

なるほど…。
