### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function add_anticache() in /var/www/html/wp-content/themes/aoyamamainland-lp1/private/functions/02_path_functions.php:12

### ISSUE THREAD

**Issue by mtmtkzm** [liginc/wordpress-frontplate#27]
debug.log
```
PHP Fatal error:  Uncaught Error: Call to undefined function add_anticache() in /var/www/html/wp-content/themes/aoyamamainland-lp1/private/functions/02_path_functions.php:12
```

内部の `add_anticache()` メソッドが定義されていないため、テーマファイルで `resolve_asset_url()` を呼び出した時点で HTMLの出力が止まってしまっているみたいです。が、何を定義すればいいかわかりません :innocent:

https://github.com/liginc/wordpress-frontplate/blob/master/wp/wp-content/themes/sampletheme/private/functions/02_path_functions.php#L12

![image](https://user-images.githubusercontent.com/13103139/45818379-87360b00-bd1c-11e8-8b5d-9578815ec3f8.png)

## 期待値？
`add_anticache()` が定義され、HTMLが出力されること
![image](https://user-images.githubusercontent.com/13103139/45818497-df6d0d00-bd1c-11e8-87f0-f6fe28690355.png)

**Comment by ktogo** [comment]
@mtmtkzm 9e3f8cd にて修正しました
